version: "3"

tasks:
  format:check:
    desc: Check formatting with Prettier
    cmds:
      - pnpm format:check

  lint:
    desc: Lint project sources
    cmds:
      - pnpm lint

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - pnpm typecheck

  test:
    desc: Run automated tests
    cmds:
      - pnpm test

  build:
    desc: Build TypeScript output
    cmds:
      - pnpm build

  docs:build:
    desc: Build VitePress docs
    cmds:
      - pnpm docs:build

  ci:
    desc: Run all quality gates
    cmds:
      - task format:check
      - task lint
      - task typecheck
      - task test
      - task build
      - task docs:build
