version: "3"

tasks:
  format:check:
    desc: Check formatting with Prettier
    cmds:
      - pnpm format:check

  lint:
    desc: Lint project sources
    cmds:
      - pnpm lint

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - pnpm typecheck

  test:
    desc: Run automated tests
    cmds:
      - pnpm test

  build:
    desc: Build TypeScript output
    cmds:
      - pnpm build

  docs:build:
    desc: Build VitePress docs
    cmds:
      - pnpm docs:build

  publish:dry-run:
    desc: Validate npm publish payload without uploading
    cmds:
      - pnpm build
      - pnpm publish --access public --dry-run

  publish:
    desc: Publish current package version to npm
    cmds:
      - pnpm build
      - pnpm publish --access public

  release:patch:
    desc: Bump patch version and publish to npm
    cmds:
      - pnpm version patch
      - task publish

  release:minor:
    desc: Bump minor version and publish to npm
    cmds:
      - pnpm version minor
      - task publish

  release:major:
    desc: Bump major version and publish to npm
    cmds:
      - pnpm version major
      - task publish

  ci:
    desc: Run all quality gates
    cmds:
      - task format:check
      - task lint
      - task typecheck
      - task test
      - task build
      - task docs:build
